version: "3.8"

services:
  nodejs:
    image: node:22.2 # Use an official Node.js image from Docker Hub
    container_name: visitorlog-app
    working_dir: /var/www/visitorlog
    volumes:
      - ./:/var/www/visitorlog # Mount your Node.js app code into the container
    ports:
      - "5000:5000" # Map container port 3000 to host port 3000
    command: npm run dev #npm start # Adjust based on your start command in package.json
    restart: always
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    # volumes:
    #   - ./data/db:/data/db
    environment:
      MONGO_INITDB_DATABASE: visitorlog
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Api2024
    restart: always
  rediscache:
    image: redis:7.2.5
    container_name: rediscache
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db

volumes:
  redis_volume_data:
  redis_insight_volume_data: